# Metadata



# BrandMeta { #brand_yml.BrandMeta }

```python
BrandMeta(**data)
```

Brand Metadata

Brand metadata is stored in `meta`, providing place to describe the company
or project, the brand guidelines, additional links, and more.

## Attributes {.doc-section .doc-section-attributes}

name

:   [BrandMetaName](`brand_yml.meta.BrandMetaName`) \| None

    The name of the brand. In the YAML, this may be a dictionary with the
    `full` and `short` forms of the brand name.

    ```yaml
    meta:
      name:
        full: Very Big Corporation of America
        short: VBCA
    ```

    or a single value as shorthand for `meta.name.full`.

    ```yaml
    meta:
      name: Very Big Corporation of America
    ```

link

:   [BrandMetaLink](`brand_yml.meta.BrandMetaLink`) \| None

    Links to additional resources related to the brand, such as its
    homepage, social media accounts, etc. Like `name`, this can be a single
    value or a dictionary with additional keys. If a single value is
    provided, it is promoted to the `home` key of
    `brand_yml.meta.BrandMetaLink`.

    These two constructions are equivalent:

    ```yaml
    meta:
      link: https://www.very-big-corp.com/
    ```

    ```yaml
    meta:
      link:
        home: https://www.very-big-corp.com/
    ```

## Notes {.doc-section .doc-section-notes}

Additional fields are allowed, so you may store any additional metadata you
want to attach to the brand here. Tools that use `brand_yml` may not know
about these fields, however.

## Examples {.doc-section .doc-section-examples}

::: {.panel-tabset}


###### Minimal

```{.yaml filename="_brand.yml"}
meta:
  name: Very Big Corp. of America
  link: https://very-big-corp.com
```



###### Full

```{.yaml filename="_brand.yml"}
meta:
  name:
    full: Very Big Corporation of America
    short: VBC
  link:
    home: https://very-big-corp.com
    mastodon: https://mastodon.social/@VeryBigCorpOfficial
    github: https://github.com/Very-Big-Corp
    linkedin: https://linkedin.com/company/very-big-corp
    twitter: https://twitter.com/VeryBigCorp
    facebook: https://facebook.com/Very-Big-Corp
```

:::

# meta.BrandMetaName { #brand_yml.meta.BrandMetaName }

```python
meta.BrandMetaName(**data)
```



## Attributes

| Name | Description |
| --- | --- |
| [full](#brand_yml.meta.BrandMetaName.full) | Full name of the company or brand. |
| [short](#brand_yml.meta.BrandMetaName.short) | Short name of the company or brand, for use in space-constrained settings. |

# meta.BrandMetaLink { #brand_yml.meta.BrandMetaLink }

```python
meta.BrandMetaLink(**data)
```

Brand Metadata Links

Links to the brand or company online and on social media sites. Links must
be the full URL to the social media profile. Additional fields are allowed,
but only the attributes listed below are validated.

## Attributes

| Name | Description |
| --- | --- |
| [bluesky](#brand_yml.meta.BrandMetaLink.bluesky) | Bluesky link for the brand or company. |
| [facebook](#brand_yml.meta.BrandMetaLink.facebook) | Facebook link for the brand or company. |
| [github](#brand_yml.meta.BrandMetaLink.github) | GitHub link for the brand or company. |
| [home](#brand_yml.meta.BrandMetaLink.home) | Home website link for the brand or company. |
| [linkedin](#brand_yml.meta.BrandMetaLink.linkedin) | LinkedIn link for the brand or company. |
| [mastodon](#brand_yml.meta.BrandMetaLink.mastodon) | Mastodon link for the brand or company. |
| [twitter](#brand_yml.meta.BrandMetaLink.twitter) | Twitter link for the brand or company. |