# read_brand_yaml { #brand_yaml.read_brand_yaml }

`read_brand_yaml(path, as_data=False)`

Read a brand YAML file

Reads a brand YAML file or finds and reads a project-specific `_brand.yml`
file and returns a validated `~brand_yaml.Brand` instance.

To find a project-specific `_brand.yaml` file, pass the project directory or
`__file__` (the path of the current Python script).
`brand_yaml.read_brand_yaml` will look in that directory or any parent
directory for a `_brand.yml`, `brand/_brand.yml` or `_brand/_brand.yml`
file. Note that it starts the search in the directory passed in and moves
upward to find the brand YAML file; it does not search into subdirectories
of the current directory.

## Parameters

<code><span class="parameter-name">path</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[str](`str`) \| [Path](`pathlib.Path`)</span></code>

:   The path to the brand YAML file or a directory where `_brand.yml` is
    expected to be found. Typically, you can pass `__file__` from the
    calling script to find `_brand.yml` in the current directory or any of
    its parent directories.

<code><span class="parameter-name">as_data</span><span class="parameter-annotation-sep">:</span> <span class="parameter-annotation">[bool](`bool`)</span> <span class="parameter-default-sep">=</span> <span class="parameter-default">False</span></code>

:   When `True`, returns the raw brand data as a dictionary parsed from the
    YAML file. When `False`, returns a validated :class:`Brand` object.

## Returns

| Type                                          | Description                                                                                                                                                                                |
|-----------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| [Brand](`brand_yaml.Brand`) \| [dict](`dict`) | A validated :class:`brand_yaml.Brand` object with all fields populated according to the brand YAML file (`as_data=False`, default) or the raw brand data as a dictionary (`as_data=True`). |

## Raises

| Type                                     | Description                                                                                                                              |
|------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------|
| [FileNotFoundError](`FileNotFoundError`) | Raises a `FileNotFoundError` if no brand configuration file is found within the given path.                                              |
| [ValueError](`ValueError`)               | `ValueError` or other validation errors are raised from [pydantic](https://docs.pydantic.dev/latest/) if the brand YAML file is invalid. |

## Examples

```python
from brand_yaml import read_brand_yaml

brand = read_brand_yaml(__file__)
brand = read_brand_yaml("path/to/_brand.yml")
```